### ISSUE TITLE
Add xpad.ko for Logitech, Inc. F310 Gamepad

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/bitcraze-raspberry-pi#1]
From the forum: http://forum.bitcraze.se/viewtopic.php?f=5&t=98&start=30#p2709

The Logitech, Inc. F310 Gamepad is not supported without a custom kernel module. The module (xpad.ko) can be downloaded here: http://bucket.changeover.za.net/xpad.ko

Download it and add it to the image.

```
#!

sudo insmod xpad.ko
```

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/raspberry-pi/issue/1
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-07-09T07:59:28.488

**Comment by ataffanel** [comment]
Should work out of the box with recent version of the raspberry pi image.
